export const NAV_LINKS = [
  { label: "À propos", href: "#about" },
  { label: "Compétences", href: "#skills" },
  { label: "Expérience", href: "#experience" },
  { label: "Projets", href: "#projects" },
  { label: "Hackathons", href: "#hackathons" },
  { label: "Contact", href: "#contact" },
];

export const STATS = [
  { value: 9, suffix: "", label: "Projets réalisés" },
  { value: 4, suffix: "", label: "Hackathons & Challenges" },
  { value: 25, suffix: "M+", label: "Lignes de données traitées" },
  { value: 20, suffix: "+", label: "Technologies maîtrisées" },
  { value: 2, suffix: "", label: "Expériences bancaires" },
  { value: 1, suffix: "", label: "Expériences cabinet(présentiel)" },
  { value: 1, suffix: "", label: "Expériences cabinet(distance)" },
];

export const SKILLS = [
  {
    icon: "🤖",
    title: "Data Science & ML",
    items: ["Machine Learning", "Deep Learning", "NLP", "Credit Scoring", "Analyse Prédictive", "Feature Engineering", "Model Validation", "Statistiques", "Classification"],
    highlight: ["Machine Learning", "Credit Scoring","NLP","Analyse Prédictive","Classification"],
  },
  {
    icon: "✨",
    title: "Intelligence Artificielle",
    items: ["IA Générative", "LLM", "RAG", "Agents IA", "Prompt Engineering", "Chatbots", "Vision IA", "Multimodal","SQL Agent","Observabilité"],
    highlight: ["IA Générative", "LLM", "RAG","Agents IA","Prompt Engineering",],
  },
  {
    icon: "⚙️",
    title: "Data Engineering",
    items: ["ETL / Pipelines", "Data Warehousing", "Big Data", "Data Quality", "Automatisation", "Excel VBA","DuckDB"],
    highlight: ["ETL / Pipelines", "Big Data",],
  },
  {
    icon: "💻",
    title: "Programmation",
    items: ["Python", "SQL", "R", "JavaScript", "Node.js", "Bash"],
    highlight: ["Python", "SQL","Node.js",],
  },
  {
    icon: "📊",
    title: "Visualisation & BDD",
    items: ["Power BI", "Plotly", "Matplotlib", "Tableau", "PostgreSQL", "MongoDB", "MySQL"],
    highlight: ["Power BI"],
  },
  {
    icon: "☁️",
    title: "Cloud & DevOps",
    items: ["Git / GitHub", "Docker", "Azure", "AWS", "GCP", "Streamlit", "FastAPI"],
    highlight: ["Docker"],
  },
];

export const EXPERIENCES = [
  {
    period: "Mars 2026 — Présent",
    company: "Société Générale Côte d'Ivoire",
    role: "Stagiaire Data Science & IA — Cellule Data",
    location: "Abidjan, CI",
    current: true,
    points: [
      { bold: "Scoring comportemental", text: " — modèles pour identifier les clients à risque de défaut." },
      { bold: "Tarification dynamique", text: " — outil complet : segmentation client → profils comportementaux → modèle tarifaire de crédit." },
      { bold: "Assistant IA Multimodal", text: " — système RAG (texte, image, audio) pour la formation interne (IA Générative)." },
      { bold: "Aide à la décision", text: " — indicateurs analytiques et reporting pour la gestion du risque." },
    ],
    tags: ["Python", "Machine Learning", "RAG", "LLM", "Credit Scoring", "Power BI"],
  },
  {
    period: "Août 2025",
    company: "SIB — Société Ivoirienne de Banque",
    role: "Stagiaire Reporting & Analyse de Données",
    location: "Abidjan, CI",
    current: false,
    points: [
      { bold: "Automatisation RH", text: " — outil Excel/VBA pour le suivi du badgeage de l'ensemble des employés." },
      { bold: "Reporting interactif", text: " — génération de rapports de présence en un clic pour la direction." },
      { bold: "Immersion bancaire", text: " — compréhension des processus opérationnels d'une grande banque ivoirienne." },
    ],
    tags: ["Excel VBA", "Automatisation", "Reporting", "RH"],
  },
    {
    period: "Avril - Septembre 2024",
    company: "Terebei - Syabe",
    role: "Stagiaire Developpeur Full stack",
    location: "Abidjan, CI",
    current: false,
    points: [
      { bold: "Developpement Backend", text: " — Mise en place de multi API pour l'alimentation d'application de gestion" },
      { bold: "Developpement Frontend", text: " — Création d'interface moderne pour pilotage de plusieurs applications" },
      { bold: "Administration BD", text: " — Création et gestion de base de données relationnelle" },
    ],
    tags: ["Node JS", "ExpressJS", "PostreSQL", "Angular", "Swagger"],
  },
  {
    period: "Mars - Septembre 2024",
    company: "ProActive SWISS - GROwing Consulting",
    role: "Formation Soft Skills en millieu professionnel et Techniques de Developpement Full stack",
    location: "Abidjan, CI (à distance)",
    current: false,
    points: [
      { bold: "Techniques de communication"},
      { bold: "Personnal Branding"},
      { bold: "Leadership"},
      { bold: "Collaboration interne"},
      { bold: "Les Microservices"},
      { bold: "L'architecture logicielle REST et les Web API's"},
    ],
    tags: [],
  },
];

export type ProjectCategory = "all" | "ml" | "ia" | "data" | "prod";

export const PROJECTS = [
  {
    id: 1,
    cat: "ia" as ProjectCategory,
    emoji: "🤖",
    category: "IA Générative · Société Générale",
    title: "Assistant IA Multimodal de Formation",
    desc: "Système RAG multimodal (texte, image, audio) déployé en interne à la SG CI. Intégration des bases documentaires bancaires pour des réponses contextuelles instantanées.",
    metrics: [{ val: "RAG", lbl: "Architecture" }, { val: "3", lbl: "Modalités" }],
    tags: ["RAG", "LLM", "Multimodal", "Python"],
    status: "Production",
    statusColor: "#16A34A",
    github: "#",
    demo: "#",
  },
  {
    id: 2,
    cat: "ml" as ProjectCategory,
    emoji: "🏆",
    category: "ML · DATATOUR 2025",
    title: "Prédiction du Défaut de Paiement",
    desc: "Compétition nationale ML — modèle entraîné sur 17M+ enregistrements, credit scoring sur 654 000 crédits. Qualifié pour la phase finale nationale.",
    metrics: [{ val: "17M+", lbl: "Enregistrements" }, { val: "654K", lbl: "Crédits scorés" }],
    tags: ["XGBoost", "Credit Scoring", "Feature Engineering", "Python"],
    status: "Finaliste National",
    statusColor: "#EA580C",
    github: "#",
    demo: null,
  },
  {
    id: 3,
    cat: "ml" as ProjectCategory,
    emoji: "📊",
    category: "Data Science · Risk Analytics",
    title: "Analyse Comportementale Clients",
    desc: "Pipeline complet sur 8,5M observations et 36 variables : prétraitement, feature engineering, segmentation, comparaison de modèles. Recommandations recouvrement & risque.",
    metrics: [{ val: "8.5M", lbl: "Observations" }, { val: "36", lbl: "Variables" }],
    tags: ["Behavioural Scoring", "Segmentation", "Python", "SQL"],
    status: "Terminé",
    statusColor: "#6B7280",
    github: "#",
    demo: null,
  },
  {
    id: 4,
    cat: "prod" as ProjectCategory,
    emoji: "🏥",
    category: "Produit IA · Santé",
    title: "Santé+360",
    desc: "Plateforme de santé intelligente pour l'Afrique : diagnostic assisté IA, accès facilité aux services de santé, suivi patient. Réduire les inégalités d'accès aux soins.",
    metrics: [],
    tags: ["IA Générative", "NLP", "Python", "FastAPI"],
    status: "En cours",
    statusColor: "#2563EB",
    github: "#",
    demo: "#",
  },
  {
    id: 5,
    cat: "prod" as ProjectCategory,
    emoji: "💼",
    category: "Produit IA · Emploi",
    title: "Emploi+360",
    desc: "Plateforme IA de mise en relation candidats-recruteurs pour le marché africain : matching intelligent, recommandations de formation, analyse du marché local.",
    metrics: [],
    tags: ["ML", "NLP", "Matching", "Node.js"],
    status: "En cours",
    statusColor: "#2563EB",
    github: "#",
    demo: null,
  },
  {
    id: 6,
    cat: "data" as ProjectCategory,
    emoji: "🌩️",
    category: "Data Engineering",
    title: "Pipeline ETL Météo Temps Réel",
    desc: "Pipeline de collecte, transformation et chargement de données météorologiques en temps réel. Orchestration automatisée, stockage structuré et dashboard dynamique.",
    metrics: [],
    tags: ["ETL", "Python", "API", "PostgreSQL"],
    status: "Opérationnel",
    statusColor: "#16A34A",
    github: "#",
    demo: null,
  },
  {
    id: 7,
    cat: "data" as ProjectCategory,
    emoji: "📡",
    category: "Data Science · Orange Think Tank",
    title: "Analyse Mobilité & Propagation",
    desc: "Pipeline multi-sources pour modéliser la propagation d'épidémies via les données de mobilité. Indicateurs analytiques et recommandations pour les décisions sanitaires.",
    metrics: [],
    tags: ["Mobilité", "Épidémiologie", "Python", "Data Viz"],
    status: "Terminé",
    statusColor: "#6B7280",
    github: "#",
    demo: null,
  },
  {
    id: 8,
    cat: "ml" as ProjectCategory,
    emoji: "🌍",
    category: "ML · GenHack 2025",
    title: "Analyse Climatique IA",
    desc: "Hackathon IA générative — modélisation des tendances climatiques, prévisions adaptatives et visualisation des impacts climatiques en Afrique par IA générative.",
    metrics: [],
    tags: ["LLM", "IA Générative", "Visualisation", "Python"],
    status: "Terminé",
    statusColor: "#6B7280",
    github: "#",
    demo: null,
  },
  {
    id: 9,
    cat: "ia" as ProjectCategory,
    emoji: "🗳️",
    category: "Agentic AI · Data Engineering",
    title: "Multi-Agent Election Intelligence Platform",
    desc: "Plateforme multi-agents pour interroger les résultats officiels des élections législatives ivoiriennes en langage naturel. SQL Agent + Hybrid RAG + LLM — 205 circonscriptions, 1 400+ candidats indexés, détection automatique d'anomalies.",
    metrics: [
      { val: "205+", lbl: "Circonscriptions" },
      { val: "1 400+", lbl: "Candidats indexés" },
    ],
    tags: ["LangChain", "DuckDB", "RAG", "SQL Agent", "Python", "Streamlit"],
    status: "Terminé",
    statusColor: "#6B7280",
    github: "#",
    demo: "#",
  },
];

export const HACKATHONS = [
  {
    icon: "🏆",
    title: "Premier National Datatour 2025",
    period: "Novembre 2025",
    role: "Data Scientist / ML Engineer",
    badge: "🥇 Finaliste National",
    badgeColor: "#EA580C",
    desc: "Compétition internationale de ML sur la prédiction du défaut de paiement. Modèle entraîné sur 17M+ données, credit scoring sur 654 000 crédits bancaires.",
    tags: ["Python", "XGBoost", "Credit Scoring", "Feature Engineering"],
    impact: "Top finaliste sur des milliers de participants",
  },
  {
    icon: "🧬",
    title: "GenHack 2025",
    period: "2025",
    role: "AI Engineer",
    badge: "Participant",
    badgeColor: "#2563EB",
    desc: "Hackathon IA générative — analyse climatique, modélisation des tendances et prévisions adaptatives pour l'Afrique subsaharienne.",
    tags: ["LLM", "IA Générative", "Python", "Visualisation"],
    impact: "Solution de modélisation climatique par IA",
  },
  {
    icon: "💡",
    title: "AbiHack 2025",
    period: "2025",
    role: "Data Scientist",
    badge: "Participant",
    badgeColor: "#2563EB",
    desc: "Hackathon local abidjanais centré sur l'innovation technologique pour résoudre des problèmes concrets du contexte ivoirien par la data et l'IA.",
    tags: ["Python", "ML", "Data Viz", "Impact Local"],
    impact: "Innovation locale par la Data & IA",
  },
  {
    icon: "📡",
    title: "Orange Think Tank Challenge",
    period: "Décembre 2025",
    role: "Data Analyst / Data Scientist",
    badge: "Participant",
    badgeColor: "#2563EB",
    desc: "Challenge sur l'analyse de mobilité et la modélisation épidémique. Pipeline multi-sources, indicateurs analytiques, recommandations sanitaires.",
    tags: ["Pipeline Data", "Mobilité", "Épidémiologie", "Python"],
    impact: "Pipeline d'aide à la décision sanitaire",
  },
];
